import type { NextConfig } from "next";

const renderRouteIncludes = [
  "./node_modules/.bin/hyperframes",
  "./node_modules/adm-zip/**/*",
  "./node_modules/agent-base/**/*",
  "./node_modules/ansi-regex/**/*",
  "./node_modules/ansi-styles/**/*",
  "./node_modules/ast-types/**/*",
  "./node_modules/@esbuild/**/*",
  "./node_modules/@hono/**/*",
  "./node_modules/@img/**/*",
  "./node_modules/@puppeteer/**/*",
  "./node_modules/@tootallnate/quickjs-emscripten/**/*",
  "./node_modules/b4a/**/*",
  "./node_modules/bare-events/**/*",
  "./node_modules/bare-fs/**/*",
  "./node_modules/bare-os/**/*",
  "./node_modules/bare-path/**/*",
  "./node_modules/bare-stream/**/*",
  "./node_modules/bare-url/**/*",
  "./node_modules/basic-ftp/**/*",
  "./node_modules/buffer-crc32/**/*",
  "./node_modules/citty/**/*",
  "./node_modules/color-convert/**/*",
  "./node_modules/color-name/**/*",
  "./node_modules/compare-versions/**/*",
  "./node_modules/chromium-bidi/**/*",
  "./node_modules/cliui/**/*",
  "./node_modules/debug/**/*",
  "./node_modules/default-browser/**/*",
  "./node_modules/define-lazy-prop/**/*",
  "./node_modules/degenerator/**/*",
  "./node_modules/devtools-protocol/**/*",
  "./node_modules/emoji-regex/**/*",
  "./node_modules/end-of-stream/**/*",
  "./node_modules/escalade/**/*",
  "./node_modules/escodegen/**/*",
  "./node_modules/esprima/**/*",
  "./node_modules/estraverse/**/*",
  "./node_modules/esutils/**/*",
  "./node_modules/events-universal/**/*",
  "./node_modules/extract-zip/**/*",
  "./node_modules/fast-fifo/**/*",
  "./node_modules/fd-slicer/**/*",
  "./node_modules/get-caller-file/**/*",
  "./node_modules/get-stream/**/*",
  "./node_modules/get-uri/**/*",
  "./node_modules/giget/**/*",
  "./node_modules/hono/**/*",
  "./node_modules/http-proxy-agent/**/*",
  "./node_modules/hyperframes/**/*",
  "./node_modules/https-proxy-agent/**/*",
  "./node_modules/ip-address/**/*",
  "./node_modules/is-fullwidth-code-point/**/*",
  "./node_modules/is-inside-container/**/*",
  "./node_modules/linkedom/**/*",
  "./node_modules/mime-types/**/*",
  "./node_modules/mitt/**/*",
  "./node_modules/ms/**/*",
  "./node_modules/nanoid/**/*",
  "./node_modules/netmask/**/*",
  "./node_modules/once/**/*",
  "./node_modules/open/**/*",
  "./node_modules/pac-proxy-agent/**/*",
  "./node_modules/pac-resolver/**/*",
  "./node_modules/pend/**/*",
  "./node_modules/picocolors/**/*",
  "./node_modules/postcss/**/*",
  "./node_modules/prettier/**/*",
  "./node_modules/progress/**/*",
  "./node_modules/proxy-agent/**/*",
  "./node_modules/proxy-from-env/**/*",
  "./node_modules/pump/**/*",
  "./node_modules/puppeteer-core/**/*",
  "./node_modules/require-directory/**/*",
  "./node_modules/semver/**/*",
  "./node_modules/sharp/**/*",
  "./node_modules/smart-buffer/**/*",
  "./node_modules/socks/**/*",
  "./node_modules/socks-proxy-agent/**/*",
  "./node_modules/source-map-js/**/*",
  "./node_modules/streamx/**/*",
  "./node_modules/string-width/**/*",
  "./node_modules/strip-ansi/**/*",
  "./node_modules/tar-fs/**/*",
  "./node_modules/tar-stream/**/*",
  "./node_modules/teex/**/*",
  "./node_modules/text-decoder/**/*",
  "./node_modules/tslib/**/*",
  "./node_modules/typed-query-selector/**/*",
  "./node_modules/webdriver-bidi-protocol/**/*",
  "./node_modules/wrappy/**/*",
  "./node_modules/wrap-ansi/**/*",
  "./node_modules/ws/**/*",
  "./node_modules/wsl-utils/**/*",
  "./node_modules/y18n/**/*",
  "./node_modules/yauzl/**/*",
  "./node_modules/yargs/**/*",
  "./node_modules/yargs-parser/**/*",
  "./node_modules/zod/**/*",
  "./hyperframes/**/*",
];
const renderRouteExcludes = [
  "./node_modules/lightningcss-linux-x64-musl/**/*",
];

const nextConfig: NextConfig = {
  allowedDevOrigins: ["127.0.0.1"],
  devIndicators: false,
  serverExternalPackages: ["hyperframes", "sharp"],
  outputFileTracingIncludes: {
    "/api/demo-videos/\\[id\\]/render": renderRouteIncludes,
    "/api/demo-videos/[id]/render": renderRouteIncludes,
  },
  outputFileTracingExcludes: {
    "/api/demo-videos/\\[id\\]/render": renderRouteExcludes,
    "/api/demo-videos/[id]/render": renderRouteExcludes,
  },
  turbopack: {
    root: process.cwd(),
  },
};

export default nextConfig;
