import {
  DemoVideoSchema,
  PitchDeckSchema,
  type CreateLaunchPackRequest,
  type DemoVideo,
  type LaunchScreenshot,
  type PitchDeck,
  type PitchPack,
  type RemotionRenderProps,
} from "./schemas";

type ReleaseInput = CreateLaunchPackRequest;

export type ReleaseAssets = {
  pitchDeck: PitchDeck;
  demoVideo: DemoVideo;
  releaseChecklist: string[];
};

const REMOTION_COMPOSITION_ID = "ProofPitchProductDemo";

function bulletList(items: string[]) {
  return items.map((item) => `- ${item}`).join("\n");
}

function escapeSlidevText(value: string) {
  return value.replace(/---/g, "- - -").trim();
}

function createDeckSlides(input: ReleaseInput, pitchPack: PitchPack) {
  const supportedClaims = pitchPack.claims.filter((claim) => claim.status !== "unsupported").slice(0, 4);
  const blockedClaims = pitchPack.claims.filter((claim) => claim.status === "unsupported").slice(0, 3);

  return [
    {
      title: input.productName,
      body: pitchPack.oneLiner,
    },
    {
      title: "Product",
      body: [`Audience: ${input.targetAudience}`, "", pitchPack.executivePitch].join("\n"),
    },
    {
      title: "Problem",
      body: pitchPack.problem,
    },
    {
      title: "Solution",
      body: pitchPack.solution,
    },
    {
      title: "Proof Ledger",
      body: supportedClaims.length
        ? bulletList(
            supportedClaims.map((claim) => `${claim.text} (${claim.status.replaceAll("_", " ")})`),
          )
        : "No supported public claims were available yet.",
    },
    {
      title: "Product Demo",
      body: bulletList([
        input.demoInstructions || "Capture the first meaningful public product workflow.",
        ...pitchPack.liveDemoSteps.slice(0, 4),
      ]),
    },
    {
      title: "Risks To Avoid",
      body: blockedClaims.length
        ? bulletList(blockedClaims.map((claim) => claim.text))
        : bulletList(pitchPack.risks.slice(0, 4)),
    },
  ];
}

export function buildSlidevMarkdown(input: ReleaseInput, pitchPack: PitchPack) {
  const slides = createDeckSlides(input, pitchPack);
  const frontmatter = [
    "---",
    "theme: default",
    `title: ${JSON.stringify(`${input.productName} release deck`)}`,
    "info: Release deck generated by ProofPitch",
    "drawings:",
    "  persist: false",
    "transition: slide-left",
    "---",
  ].join("\n");
  const markdownSlides = slides.map((slide, index) =>
    [
      index === 0 ? `# ${escapeSlidevText(slide.title)}` : `## ${escapeSlidevText(slide.title)}`,
      "",
      escapeSlidevText(slide.body),
    ].join("\n"),
  );

  return {
    markdown: [frontmatter, ...markdownSlides].join("\n\n---\n\n"),
    slideCount: slides.length,
  };
}

function createRenderProps({
  input,
  pitchPack,
  screenshots,
}: {
  input: ReleaseInput;
  pitchPack: PitchPack;
  screenshots: LaunchScreenshot[];
}): RemotionRenderProps {
  return {
    productName: input.productName,
    oneLiner: pitchPack.oneLiner,
    sourceUrl: input.sourceUrl,
    screenshots: screenshots.map((screenshot) => ({
      title: screenshot.title,
      url: screenshot.url,
      alt: screenshot.alt,
    })),
    demoSteps: [
      `Open ${input.productName} at ${input.sourceUrl}.`,
      input.demoInstructions || "Show the first meaningful public product workflow.",
      ...pitchPack.liveDemoSteps.slice(0, 3),
    ],
    captions: [
      `${input.productName}: ${pitchPack.oneLiner}`,
      "Product demo and pitch deck are separate assets.",
      "Unsupported claims stay visible before publishing.",
    ],
  };
}

function buildDemoVideo({
  input,
  pitchPack,
  screenshots,
  captureVideoUrl,
}: {
  input: ReleaseInput;
  pitchPack: PitchPack;
  screenshots: LaunchScreenshot[];
  captureVideoUrl?: string;
}) {
  const renderProps = createRenderProps({ input, pitchPack, screenshots });

  if (captureVideoUrl) {
    return DemoVideoSchema.parse({
      status: "ready",
      url: captureVideoUrl,
      uploadStatus: "uploaded",
      durationSeconds: 60,
      renderer: "remotion",
      compositionId: REMOTION_COMPOSITION_ID,
      renderProps,
    });
  }

  return DemoVideoSchema.parse({
    status: "pending",
    uploadStatus: "blocked_by_provider_review",
    durationSeconds: 0,
    renderer: "remotion",
    compositionId: REMOTION_COMPOSITION_ID,
    renderProps,
    error:
      "Product demo video requires Playwright capture. Set PROOFPITCH_PLAYWRIGHT_CAPTURE=1 in a worker that can record the product workflow.",
  });
}

export async function buildReleaseAssets({
  input,
  pitchPack,
  screenshots,
  captureVideoUrl,
}: {
  input: ReleaseInput;
  pitchPack: PitchPack;
  screenshots: LaunchScreenshot[];
  captureVideoUrl?: string;
}): Promise<ReleaseAssets> {
  const { markdown, slideCount } = buildSlidevMarkdown(input, pitchPack);
  const pitchDeck = PitchDeckSchema.parse({
    status: "ready",
    format: "slidev",
    title: `${input.productName} release deck`,
    slideCount,
    markdown,
    exports: [
      {
        format: "pdf",
        status: "pending",
      },
      {
        format: "png",
        status: "pending",
      },
    ],
  });

  return {
    pitchDeck,
    demoVideo: buildDemoVideo({ input, pitchPack, screenshots, captureVideoUrl }),
    releaseChecklist: [
      "Review the product demo capture before external use.",
      "Review the Slidev pitch deck separately from the product demo video.",
      "Remove unsupported claims before sharing the pack.",
    ],
  };
}
